{
  "comments": [
    {
      "key": {
        "uuid": "1a76adc5_4eff2935",
        "filename": "appc-common/src/test/java/org/onap/appc/concurrent/TestSignal.java",
        "patchSetId": 1
      },
      "lineNbr": 154,
      "author": {
        "id": 811
      },
      "writtenOn": "2018-08-06T12:30:13Z",
      "side": 1,
      "message": "remove try-catch wrapper",
      "revId": "afa7e7da26bbacecdefbd3aecc97616e15912d21",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a76adc5_3fda1579",
        "filename": "appc-common/src/test/java/org/onap/appc/concurrent/TestSignal.java",
        "patchSetId": 1
      },
      "lineNbr": 154,
      "author": {
        "id": 1089
      },
      "writtenOn": "2018-08-06T20:14:48Z",
      "side": 1,
      "message": "cant remove try catch here..because exception is thrown by the method mySignal.waitForAny() and as a result of this, the test case fails because assertEquals never gets called.",
      "parentUuid": "1a76adc5_4eff2935",
      "revId": "afa7e7da26bbacecdefbd3aecc97616e15912d21",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}